### ISSUE TITLE
UUAppReg 400

### ISSUE THREAD

**Issue by ShannonPaige** [edgarduran/traffic-spy-skeleton#2]
As an unregistered user
When I send a request to http://localhost:9393/sources
  with the data identifier but without rootURL 
I expect to see a response of "Missing Parameters - 400 Bad Request"

**Comment by ShannonPaige** [comment]
OR
As an unregistered user
When I send a request to http://localhost:9393/sources
  with the rootURL but without data identifier 
I expect to see a response of "Missing Parameters - 400 Bad Request"
OR 
As an unregistered user
When I send a request to http://localhost:9393/sources
  but without rootURL or identifier 
I expect to see a response of "Missing Parameters - 400 Bad Request"

**Comment by edgarduran** [comment]
Views:
CL?
